import Providers from "../lib/providers";
import Nav from "../components/Nav";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <Nav />
      </body>
    </html>
  );
}
